micronaut:
  application:
    name: contaService
datasources:
  default:
    url: jdbc:mysql://localhost:3306/conta
    username: root
    password: root
    dialect: MYSQL
jpa:
  default:
    packages-to-scan:
      - 'com.github.fabriciolfj.domain.entities'
    properties:
      hibernate:
        hbm2ddl:
          auto: none
        show_sql: true

flyway:
  datasources:
    default:
      enabled: true
      locations:
        - classpath:db/migration
        - classpath:db/testdata
